### ISSUE TITLE
ENS220 Arduino 1KHz I2C Read Setup

### ISSUE THREAD

**Issue by Ianhtaylor** [sciosense/ens220-arduino#2]
Hi, could you please add more information and diagram on how to properly setup the pinouts for using the 1kHz I2C read functionality.

**Comment by TRScioSense** [comment]
Hello Ianhtaylor,
there is not special attention required to run ENS220 at 1kHz I2C speed.
- wiring: please follow our [datasheet ](https://www.sciosense.com/wp-content/uploads/2023/12/ENS220-Datasheet.pdf) section 9
- setup clock speed: as the clock is provided by the master device (your µC) please set the according registers with proper values. In case you're using e.g. ATMega based controllers (Arduino Nano/Uno etc) you can simply follow our [AN ](https://www.sciosense.com/wp-content/uploads/2024/07/ENS21x-Application-Note-using-an-ENS21x-on-long-wire-IC-cable.pdf )also describing how to reduce clock speed. Here you only need to change TWBR and TWSR register as follows after the `Wire.begin()` instruction:
`    TWBR = 0x7D;
    uint8_t TWPS = 3;
    TWSR = (TWSR & 0x03)| TWPS;`
This will set the clock speed to 1kHz and you can communicate as usual
